config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get 'about', to: 'pages#About'
  resources :articles


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end
  def create
    @article = Article.new(article_params)
  if  @article.save
    flash[:notice] = "Articles was successfully created"
    redirect_to articles_path(@article)
  else  render 'new'
   end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

def update
  @article = Article.find(params[:id])
  if @article.update(article_params)
    flash[:notice] = "Article was updated"
    redirect_to articles_path(@article)
  else
    flash[:notice] = "Artice was not updated"
    render 'edit'
  end

end

def index
  @articles = Article.all
end

private
def article_params
  params.require(:article).permit(:title, :description)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_controller_helper.rb
module PagesControllerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article<h1>
  <%= if @article.errors.any? %>
    <h2>The following errors prevented the article from saving:</h2>
    <ul>
      <%= @article.errors.full_messages.each do |msg|%>
      <li> <%= msg %><li>
        <% end %>
    <ul>
      <% end %>

<%= form_for @article do |f| %>
<p>
<%= f.label :title %><br>
<%= f.text_field :title %>
<p>
<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
<p>
  <p>
    <%= f.submit %>
   </p>
  <% end %>

app/views/articles/index.html.erb
<h1> listing all articles </h1>
<table>
  <tr>
    <th>title</th>
    <th>description</th>
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
  </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>create an article<h1>
  <%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  <P>
    <p>
      <%= f.submit %>
    </p>

  <% end %>
<% if @article.errors.any? %>
<h2> The following errors prevented the article from saving : <h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %><li>
      <% end %>
  <ul>
<% end %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<p>
 Title: <%= @article.title %>
</p>
<p>
 Description: <%= @article.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogMedium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %><li>
    </ul>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Blog<h1>
<%=link to 'home', root_path %>

app/views/pages/index.html.erb
<h1> hey welcom to the jungle<h1>
  <%= link_to 'about',about_path %>